// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "../../v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/util/tokens.h"

// Custom token header file
#include "app-custom-application/gw-cfg-tokens.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

