// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __AF_GEN_EVENT__
#define __AF_GEN_EVENT__


// Code used to configure the cluster event mechanism
#define EMBER_AF_GENERATED_EVENT_CODE \
  extern EmberEventControl appNetworkJoinEventControl; \
  extern EmberEventControl appPowerOnEventControl; \
  extern EmberEventControl appRebootEventControl; \
  extern EmberEventControl deviceMonitorEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentReceiveEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentTransmitEventControl; \
  extern EmberEventControl emberAfPluginNetworkSteeringFinishSteeringEventControl; \
  extern EmberEventControl emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl; \
  extern EmberEventControl halRebootEventControl; \
  extern EmberEventControl redLedSteadyOnTimeEventControl; \
  extern EmberEventControl yhSetNetDataEvenControl; \
  extern void appNetworkJoinHandler(void); \
  extern void appPowerOnHandler(void); \
  extern void appRebootEventHandler(void); \
  extern void deviceMonitorHandler(void); \
  extern void emberAfPluginInterpanFragmentReceiveEventHandler(void); \
  extern void emberAfPluginInterpanFragmentTransmitEventHandler(void); \
  extern void emberAfPluginNetworkSteeringFinishSteeringEventHandler(void); \
  extern void emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler(void); \
  extern void halRebootEventHandler(void); \
  extern void redLedSteadyOnTimeHandler(void); \
  extern void yhSetNetDataEventHandler(void); \
  static void networkEventWrapper(EmberEventControl *control, EmberAfNetworkEventHandler handler, uint8_t networkIndex) \
  { \
    emberAfPushNetworkIndex(networkIndex); \
    emberEventControlSetInactive(*control); \
    (*handler)(); \
    emberAfPopNetworkIndex(); \
  } \
  EmberEventControl emberAfPluginScanDispatchScanNetworkEventControls[1]; \
  extern void emberAfPluginScanDispatchScanNetworkEventHandler(void); \
  void emberAfPluginScanDispatchScanNetworkEventWrapper0(void) { networkEventWrapper(&emberAfPluginScanDispatchScanNetworkEventControls[0], emberAfPluginScanDispatchScanNetworkEventHandler, 0); } \


// EmberEventData structs used to populate the EmberEventData table
#define EMBER_AF_GENERATED_EVENTS   \
  { &appNetworkJoinEventControl, appNetworkJoinHandler }, \
  { &appPowerOnEventControl, appPowerOnHandler }, \
  { &appRebootEventControl, appRebootEventHandler }, \
  { &deviceMonitorEventControl, deviceMonitorHandler }, \
  { &emberAfPluginInterpanFragmentReceiveEventControl, emberAfPluginInterpanFragmentReceiveEventHandler }, \
  { &emberAfPluginInterpanFragmentTransmitEventControl, emberAfPluginInterpanFragmentTransmitEventHandler }, \
  { &emberAfPluginNetworkSteeringFinishSteeringEventControl, emberAfPluginNetworkSteeringFinishSteeringEventHandler }, \
  { &emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl, emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler }, \
  { &halRebootEventControl, halRebootEventHandler }, \
  { &redLedSteadyOnTimeEventControl, redLedSteadyOnTimeHandler }, \
  { &yhSetNetDataEvenControl, yhSetNetDataEventHandler }, \
  { &emberAfPluginScanDispatchScanNetworkEventControls[0], emberAfPluginScanDispatchScanNetworkEventWrapper0 }, \


#define EMBER_AF_GENERATED_EVENT_STRINGS   \
  "App network join event control",  \
  "App power on event control",  \
  "App reboot event control",  \
  "Device monitor event control",  \
  "Interpan Plugin FragmentReceive",  \
  "Interpan Plugin FragmentTransmit",  \
  "Network Steering Plugin FinishSteering",  \
  "Update TC Link Key Plugin BeginTcLinkKeyUpdate",  \
  "Hal reboot event control",  \
  "Red led steady on time event control",  \
  "Yh set net data even control",  \
  "Scan Dispatch Plugin Scan NWK 0", \


#endif // __AF_GEN_EVENT__
